### ISSUE TITLE
Per-device sun elevation angle

### ISSUE THREAD

**Issue by dfifield** [slisovski/TheGeolocationManual#5]
Removed

**Comment by slisovski** [comment]
Dear Dave,
Thanks heaps for your email.
Your suggested edits are very welcome.
Cheers,
Simeon

On 30. Sep 2023, at 14:16, Dave Fifield ***@***.***> wrote:



Firstly, thank-you for this outstanding manual and the paper (Lisovski et al. 2020)!

I would like to propose a clarification on the use of separate sun elevation angles (computed from calibration data) for each individual device in a study. If I understand section "4.2 Step 2: Calibration" of Lisovski et al 2020, you are advising that researchers should calculate a separate sun elevation angle for each device based on it's calibration data. I understand that this is needed to account for any device-specific inaccuracies in recording of light intensity, and individual device-specific shading etc, and I have always done my analyses this way.

However, when working with other researchers, I have often come across the idea that a single "average" sun elevation should be chosen and applied to all devices in a given study in order to make the analysis "standardized" or "consistent" across devices. I believe this is a misconception and in fact achieves the opposite of what is intended by biasing the results of some (or all) devices. I am currently working on a project to compare analysis techniques (GeoLight, probGLS, SGAT, etc) for a sample of GLS devices from a seabird species and it has been suggested that we use 1 single sun elevation angle for all analyses/devices. I would like to be able to point to text in the manual that advises against this.

Although I think the advice in section 4.2 of your paper is reasonably clear, I think this point could be made explicitly clear in the manual sections on Calibration for each analysis type by adding a sentence or two to each of these sections (or perhaps just once in the Getting Started section?) that explicitly states that the advised analysis process is to compute a separate sun elevation angle for each device (assuming calibration data is available). It could even explain why choosing a single omnibus angle to use for all devices is ill-advised.

I'd be happy craft some sentences and add them to the manual and issue a pull request if you think this would be beneficial. But, before I do that can you confirm that computing separate per-device sun elevation angles is what you intended in Section 4.2 of the paper or have I misinterpreted?

Thanks!
Dave Fifield
am proposing to modify the Calibration section of Chapter 5 of this manual to explicitly state that the choice of sun elevation angle through calibration should be done on a per device basis. I'd be happy to craft a single sentence (or two)

**Comment by dfifield** [comment]
Hi Simeon,

Ok great - I'll try to put something together in the next week or so and then send a pull request allowing you to review/discuss.

Best!
Dave

Dave Fifield
Marine Wildlife and Ecosystem Conservation Specialist
Wildlife Research Division, Science and Technology Branch
Environment and Climate Change Canada / Government of Canada
***@***.*** / Tel: 709-772-4415 / Cell: 709-725-5301

Spécialiste de la conservation de la faune et de l'écosystème marins
Division de la recherche sur la faune, Direction générale des sciences et technologie
Environnement et Changement Climatique Canada / Gouvernement du Canada
***@***.*** / Tél. : 709-772-4415 / Tél. cell. : 709-725-5301

***@***.***
